### ISSUE TITLE
Hook woocommerce_mnm_loaded is deprecated since version 2.0.0! Use wc_mnm_loaded instead.

### ISSUE THREAD

**Issue by v-marinkov** [helgatheviking/wc-mnm-container-step#3]
The plugin is throwing multiple warnings since the 2.0.0 update including `woocommerce_mnm_loaded, woocommerce_mnm_add_to_cart_parameters, woocommerce_mix_and_match_data_attributes` and potentially others.

**Comment by helgatheviking** [comment]
Thanks for the report. All the mix and match mini-extensions need updating for 2.0. I've been making my way through them as I am able. Open to any help on those.

**Comment by helgatheviking** [comment]
@v-marinkov ps- have you checked out the [grouped](https://github.com/kathyisawesome/wc-mnm-grouped) mini-extension? It approximates variable mix and match by grouping multiple mix and match products together in a way that the customer must first select which product to fill. 

This came along well after this container stop plugin, and I think this is a much better UX for the customer... plus it would allow you to better handle shipping/pricing for the different increments.

In fact, I think it might be so much better that I am going to consider archiving this and pointing folks to Grouped instead. Is there a use case you have that couldn't be handled by a Grouped (Variable-ish) use case?
